export enum RequestState {
  SUBMITTED                = 'SUBMITTED',
  PENDING_HCM              = 'PENDING_HCM',
  NEEDS_RECONCILIATION     = 'NEEDS_RECONCILIATION',
  APPROVED                 = 'APPROVED',
  REJECTED_PRE_VALIDATION  = 'REJECTED_PRE_VALIDATION',
  REJECTED_HCM             = 'REJECTED_HCM',
  REJECTED_INVALID         = 'REJECTED_INVALID',
  FAILED_CREDENTIAL_ERROR  = 'FAILED_CREDENTIAL_ERROR',
  FAILED_EXHAUSTED         = 'FAILED_EXHAUSTED',
}
